config/routes.rb
Rails.application.routes.draw do
  get 'page/index'
  get 'page/home'
  resources :maintenances
  resources :materials
  resources :engines
  resources :cities
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "page#index"
end

app/models/engine.rb
class Engine < ApplicationRecord

    has_one_attached :image    
 end

app/controllers/engines_controller.rb
class EnginesController < ApplicationController
  before_action :set_engine, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  before_action only: [:edit, :update ,:destroy ,:create] do
    authorize_request(["admin"])
   end

  # GET /engines or /engines.json
  def index
      
    @pagy, @engines = pagy(Engine.all) 

  end

  # GET /engines/1 or /engines/1.json
  def show
  end

  # GET /engines/new
  def new
    @engine = Engine.new
  end

  # GET /engines/1/edit
  def edit
  end

  # POST /engines or /engines.json
  def create
    @engine = Engine.new(engine_params)

    respond_to do |format|
      if @engine.save
        format.html { redirect_to engine_url(@engine), notice: "Engine was successfully created." }
        format.json { render :show, status: :created, location: @engine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engines/1 or /engines/1.json
  def update
    respond_to do |format|
      if @engine.update(engine_params)
        format.html { redirect_to engine_url(@engine), notice: "Engine was successfully updated." }
        format.json { render :show, status: :ok, location: @engine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engines/1 or /engines/1.json
  def destroy
    @engine.destroy

    respond_to do |format|
      format.html { redirect_to engines_url, notice: "Engine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engine
      @engine = Engine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def engine_params
      params.require(:engine).permit(:type, :name, :description, :image)
    end
end

app/helpers/engines_helper.rb
module EnginesHelper
end

app/views/engines/_engine.html.erb
<div id="<%= dom_id engine %>">
  <p>
    <strong>Type:</strong>
    <%= engine.engine_type %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= engine.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= engine.description %>
  </p>
  <p>
 



    <% if engine.image.persisted? %>
    <%=  image_tag engine.image,    width: "20%"   %> 
    <% else%>
    <img src="https://placehold.co/40x40" alt="Avatar",  width="20%" >

    <% end %>




  </p>

</div>

app/views/engines/_form.html.erb
<%= form_with(model: engine) do |form| %>
  <% if engine.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(engine.errors.count, "error") %> prohibited this engine from being saved:</h2>

      <ul>
        <% engine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :engine_type, style: "display: block" %>
    <%= form.text_field :engine_type, :required => true %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name , :required => true%>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description , :required => true%>
  </div>
 
<div >
  <%= form.label :image, style:"display: block" %>
  <%= form.file_field :image, :required => true %>
</div>

 
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/engines/edit.html.erb
<h1>Editing engine</h1>

<%= render "form", engine: @engine %>

<br>

<div>
  <%= link_to "Show this engine", @engine %> |
  <%= link_to "Back to engines", engines_path %>
</div>

app/views/engines/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Engines</h1>

<div id="engines">
  <% @engines.each do |engine| %>
    <%= render engine %>
    <p>

      <%= link_to "Show this engine", engine %>
      
    </p>
  <% end %>
</div>
<%== pagy_nav(@pagy) if @pagy.pages > 1 %>
<%= link_to "New engine", new_engine_path %>

app/views/engines/new.html.erb
<h1>New engine</h1>

<%= render "form", engine: @engine %>

<br>

<div>
  <%= link_to "Back to engines", engines_path %>
</div>

app/views/engines/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @engine %>

<div>
  <%= link_to "Edit this engine", edit_engine_path(@engine) %> |
  <%= link_to "Back to engines", engines_path %>

  <%= button_to "Destroy this engine", @engine, method: :delete %>
</div>