config/routes.rb
Rails.application.routes.draw do
  get 'page/index'
  get 'page/home'
  resources :maintenances
  resources :materials
  resources :engines
  resources :cities
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "page#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "JetMaintain", root_path, :class=>"navbar-brand nav-link active text-white" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= root_path %>">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to "Motors", engines_path ,class:"nav-link"%>

        </li>
        <li class="nav-item">
          <%= link_to "Maintenance", maintenances_path ,class:"nav-link"%>

        </li>
        <li class="nav-item">
          <%= link_to "Terminos & Condiciones", page_home_path ,class:"nav-link"%>
        </li>
             
      </ul>
 

<ul class="navbar-nav ms-auto mb-5 mb-lg-0">
  <li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
<% if user_signed_in? %> 
<%= current_user.role %>    
<% else %> Dale registrate o conectate 
<% end %> </a>
<ul class="dropdown-menu">
<% if user_signed_in? %>
    <li>
    <%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item',method: :delete %>
    </li>
    <li>
    <%= link_to 'Editar Perfil', edit_user_registration_path, class: 'dropdown-item'%>
    </li>
    <% else %> 
    <li>
    <%= link_to 'Iniciar sesión', new_user_session_path, class: 'dropdown-item'%>
    </li>
    <li>
    <hr class="dropdown-divider">
    </li>
    <li><%= link_to 'Registro', new_user_registration_path, class: 'dropdown-item'%> </li><% end %>
    </ul>
    </li>
</ul>



    </div>
  </div>
</nav>