config/routes.rb
Rails.application.routes.draw do
  get 'page/index'
  get 'page/home'
  resources :maintenances
  resources :materials
  resources :engines
  resources :cities
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "page#index"
end

app/models/maintenance.rb
class Maintenance < ApplicationRecord
  belongs_to  :engine
  belongs_to  :city
  belongs_to  :user
  has_and_belongs_to_many :materials


  enum type: [:preventive, :corrective]

end

app/controllers/maintenances_controller.rb
class MaintenancesController < ApplicationController
  before_action :set_maintenance, only: %i[ show edit update destroy ]
  before_action :set_materials, only: %i[ new edit create update]
  before_action :set_cities, only: %i[ new edit create update]
  before_action :set_engines, only: %i[ new edit create update]
  before_action :authenticate_user!, except: %i[ new edit create update ]

  before_action only: [:destroy ] do
    authorize_request(["operador"])
   end



  # GET /maintenances or /maintenances.json
  def index
    @maintenances = Maintenance.all
  end

  # GET /maintenances/1 or /maintenances/1.json
  def show
  end

  # GET /maintenances/new
  def new
    @maintenance = Maintenance.new
  end

  # GET /maintenances/1/edit
  def edit
  end

  # POST /maintenances or /maintenances.json
  def create
    @maintenance = Maintenance.new(maintenance_params)

    respond_to do |format|
      if @maintenance.save
        format.html { redirect_to maintenance_url(@maintenance), notice: "Maintenance was successfully created." }
        format.json { render :show, status: :created, location: @maintenance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @maintenance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maintenances/1 or /maintenances/1.json
  def update
    respond_to do |format|
      if @maintenance.update(maintenance_params)
        format.html { redirect_to maintenance_url(@maintenance), notice: "Maintenance was successfully updated." }
        format.json { render :show, status: :ok, location: @maintenance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @maintenance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maintenances/1 or /maintenances/1.json
  def destroy
    @maintenance.destroy

    respond_to do |format|
      format.html { redirect_to maintenances_url, notice: "Maintenance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maintenance
      @maintenance = Maintenance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def maintenance_params
      params.require(:maintenance).permit(:typeengine, :namemaintence, :dateexecute, :engines_id, :cities_id, :users_id,:materials_ids => [])
    end


    def set_materials
      @materials = Material.all
     end

     def set_cities
      @cities = City.all
     end

     def set_engines
      @engines = Engine.all
    end

end

app/helpers/maintenances_helper.rb
module MaintenancesHelper
end

app/views/maintenances/_form.html.erb
<%= form_with(model: maintenance) do |form| %>
  <% if maintenance.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(maintenance.errors.count, "error") %> prohibited this maintenance from being saved:</h2>

      <ul>
        <% maintenance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
    <div > 
  <%= form.label :typeengine, style: "display: block" %>
   <select id="tipoMantenimiento" name="tipoMantenimiento"  , :required => true >
            <option value="Preventivo">Motor a reacción</option>
            <option value="Correctivo">Motor turbohélice</option>
</select>
   </div>
 

  <div>
    <%= form.label :dateexecute, style: "display: block" %>
    <%= form.date_field :dateexecute , :required => true %>
  </div>

   <div > 
  <%= form.label :tipoMantenimiento, "Tipo Mantenimiento", style: "display: block" %>
   <select id="tipoMantenimiento" name="tipoMantenimiento"  , :required => true >
            <option value="Preventivo">Preventivo</option>
            <option value="Correctivo">Correctivo</option>
</select>
   </div>

  <div>
 
    <%= form.label :engines_id, "Motor", style: "display: block" %>
    <%= form.collection_select :engines_id, @engines, :id, :name , :required => true%>
  
  </div>

  <div class="mt-3">
    <%= form.label :cities_id, "Ciudad", style: "display: block" %>
    <%= form.collection_select :cities_id, @cities, :id, :name, :required => true%>
  </div>
  <div>
    <%= form.label :users_id, style: "display: block" %>
    <%= form.label current_user.id  %>
  </div>
 
    <div>
      <%= form.label :materials_ids, style: "display: block", class: "form-group" %>
        <div class="row">
        <%= form.collection_check_boxes(:material_ids, @materials, :id, :name) do |b| %>
          <div class="col-md-2">
          <span class="w100 form-control my-2"><%= b.label { b.check_box + " " + b.text }
          %></span>
          </div>
        <% end %>
        </div>
      </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/maintenances/_maintenance.html.erb
<div id="<%= dom_id maintenance %>">
  <p>
    <strong>Typeengine:</strong>
    <%= maintenance.typeengine %>
  </p>

  <p>
    <strong>Namemaintence:</strong>
    <%= maintenance.namemaintence %>
  </p>

  <p>
    <strong>Dateexecute:</strong>
    <%= maintenance.dateexecute %>
  </p>

  <p>
    <strong>Engines:</strong>
    <%= maintenance.engines_id %>
  </p>

  <p>
    <strong>Cities:</strong>
    <%= maintenance.cities_id %>
  </p>

  <p>
    <strong>Users:</strong>
    <%= maintenance.users_id %>
  </p>
  <div>
  <%= form.label :materials, style: "display: block" %>
  <%= form.select :materials_ids, options_from_collection_for_select(@materials,:id, :name) %>
</div>

</div>

app/views/maintenances/edit.html.erb
<h1>Editing maintenance</h1>

<%= render "form", maintenance: @maintenance %>

<br>

<div>
  <%= link_to "Show this maintenance", @maintenance %> |
  <%= link_to "Back to maintenances", maintenances_path %>
</div>

app/views/maintenances/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Maintenances</h1>

<div id="maintenances">
  <% @maintenances.each do |maintenance| %>
    <%= render maintenance %>
    <p>
      <%= link_to "Show this maintenance", maintenance %>
    </p>
  <% end %>
</div>

<%= link_to "New maintenance", new_maintenance_path %>

app/views/maintenances/new.html.erb
<h1>New maintenance</h1>

<%= render "form", maintenance: @maintenance %>

<br>

<div>
  <%= link_to "Back to maintenances", maintenances_path %>
</div>

app/views/maintenances/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @maintenance %>

<div>
  <%= link_to "Edit this maintenance", edit_maintenance_path(@maintenance) %> |
  <%= link_to "Back to maintenances", maintenances_path %>

  <%= button_to "Destroy this maintenance", @maintenance, method: :delete %>
</div>